version: "3"

#name: social-network
services:
  gateway:
    container_name: social-gateway
    image: social-gateway:0.0.1
    ports:
      - "8090:8080"
    environment:
      GATEWAY_PORT: 8080
      GATEWAY_USER_URL: http://users:8081/
      GATEWAY_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - users
    networks:
      - social

  users:
    container_name: social-users
    image: social-users:0.0.2
#    ports:
#      - "8008:8080"
    environment:
      USER_ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      USER_SERVICE_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - psql
    networks:
      - social
      - psql-network

  ### Database ###
  psql:
    image: postgres:15
    container_name: social-psql
    #    ports:
    #      - "внешний : внутренний"
    #      - "5001:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      #      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - psql-network

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: social-pgadmin
    ports:
      - "9080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    depends_on:
      - psql
    networks:
      - psql-network

networks:
  social:
    driver: bridge
    external: true
  psql-network:
    driver: bridge
    external: true

volumes:
  elasticsearch_data:
    driver: local
