version: "3"

#name: social-metrics
services:
  grafana:
    build: './prometheus'
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - social

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus:/prometheus
    networks:
      - social

networks:
  social:
    driver: bridge
    external: true