kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.database.host }}
  ports:
    - name: port
      port: {{ .Values.database.port }}5432
